# Application settings
app_name: krisha-crm-backend
app_port: 8034
health_check_path: "/health"
env: development

# Domain configuration
# domain: krishabackend.vasifytech
domain: krishabackend.vasifytech.com
# Target machine (must match inventory.yml)
target_host: vt-prod-app-02

# SSL settings
ssl_email: yogendra@vasifytech.com

# Docker registry (GitLab) 
registry: registry.gitlab.com
registry_image: registry.gitlab.com/vasify/client-projects/akuabeat/akuabeat-crm/krisha-crm-backend
